GET http://localhost:3001/api

###

POST http://localhost:3001/api
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

GET http://localhost:3001/measurements

###

GET http://localhost:3001/measurements?id=87



###

GET http://localhost:3001/farms

###

GET http://localhost:3001/farmslatest

###

GET http://localhost:3001/farmslatest2

